### ISSUE TITLE
Deprecated syntax in exception handling in monitors.py

### ISSUE THREAD

**Issue by pkicsiny** [PyCOMPLETE/PyHEADTAIL#142]
`
Traceback (most recent call last):
  File "BeamBeam4DAtTwoIPs.py", line 71, in <module>
    B1b1.addElementToPipeline(BunchMonitor(filename=f'B1b1',n_steps=nTurn))
  File "/Users/pkicsiny/phd/cern/git/PyHEADTAIL/PyHEADTAIL/monitors/monitors.py", line 74, in __init__
    self._create_file_structure(parameters_dict)
  File "/Users/pkicsiny/phd/cern/git/PyHEADTAIL/PyHEADTAIL/monitors/monitors.py", line 129, in _create_file_structure
    self.warns(err.message)
AttributeError: 'BlockingIOError' object has no attribute 'message'
`

The issue is also described [here](https://github.com/Grokzen/redis-py-cluster/issues/278) in another context.

`err.message` should be replaced everywhere by `str(err)`.

**Comment by lmether** [comment]
Fixed in [v1.16.0](https://github.com/PyCOMPLETE/PyHEADTAIL/releases/tag/v1.16.0)
